spring:
  application:
    name: eureka-server
server:
  port: 9000
eureka:
  instance:
    hostname: luandeptrai.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
